#pragma once

#include "expressions/Expression.h"
#include "expressions/NumberExpression.h"
#include "expressions/AddExpression.h"
#include "expressions/MulExpression.h"
#include "expressions/DivExpression.h"
#include "expressions/SubstractExpression.h"
#include "expressions/IdentExpression.h"
#include "assignments/Assignment.h"
#include "assignments/AssignmentList.h"

// #include "assignments_default/assignment.h"
// #include "assignments_default/assignment_list.h"
// #include "expression_default/addexpression.h"
// #include "expression_default/divexpression.h"
// #include "expression_default/expression.h"
// #include "expression_default/mulexpression.h"
// #include "expression_default/subexpression.h"
// #include "expression_template/addexpression.h"
// #include "expression_template/divexpression.h"
// #include "expression_template/expression.h"
// #include "expression_template/mulexpression.h"
// #include "expression_template/subexpression.h"